name: dating
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.6.1
  image_picker: ^1.1.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  twitter_login: ^4.4.2
  provider: ^6.1.2
  intl_phone_field: ^3.2.0
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  shared_preferences: ^2.2.3
  otp_text_field: ^1.1.3
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  #  cached_network_image: ^3.3.1
  #  flutter_localization: ^0.2.0
  lottie: ^3.1.2
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2
  intl: ^0.18.1
  agora_rtc_engine: ^6.3.1
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.0
  share_plus: ^9.0.0
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3
  flutter_widget_from_html_core: ^0.14.12
  camera: ^0.11.0
  camera_android_camerax: ^0.6.5+2
  webview_flutter: ^3.0.4
  flutter_spinkit: ^5.2.1
  http_auth: ^1.0.4
  get: ^4.6.6
  onesignal_flutter: ^3.5.0
  http: ^1.2.1
  fluttertoast: ^8.2.4
  razorpay_flutter: ^1.3.7

dev_dependencies:

  flutter_lints: ^4.0.0
  dependency_validator: ^4.0.0 # dart run dependency_validator

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/Image/
    - assets/Image/logo.png
    - assets/Image/logo-dark.png
    - assets/Image/logo-black.png
    - assets/lottie/
    - lang/

  fonts:
    - family: Satoshi-Regular
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
    - family: Satoshi-Bold
      fonts:
        - asset: assets/fonts/Satoshi-Bold.otf
    - family: Satoshi-Medium
      fonts:
        - asset: assets/fonts/Satoshi-Medium.otf
    - family: Satoshi-Black
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf